# Generated by Django 4.2.5 on 2023-09-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_client_secret",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="секретный ключ платежа пользователя",
            ),
        ),
    ]
